package com.lxy.mapper;

import java.util.List;
import java.util.Map;

import com.lxy.model.LxyCompanyNews;

public interface LxyCompanyNewsMapper {
	
	List<LxyCompanyNews> getNewsByParam(Map<String, Object> param);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int deleteByPrimaryKey(Long newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int insert(LxyCompanyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int insertSelective(LxyCompanyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    LxyCompanyNews selectByPrimaryKey(Long newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int updateByPrimaryKeySelective(LxyCompanyNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_company_news
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int updateByPrimaryKey(LxyCompanyNews record);
}