package com.lxy.mapper;

import java.util.List;
import java.util.Map;

import com.lxy.model.LxyProductDetail;

public interface LxyProductDetailMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int deleteByPrimaryKey(Long detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insert(LxyProductDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insertSelective(LxyProductDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	LxyProductDetail selectByPrimaryKey(Long detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKeySelective(LxyProductDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKey(LxyProductDetail record);

	public List<LxyProductDetail> getImgPaths(Map<String, Object> param);
}