package com.lxy.mapper;

import com.lxy.model.LxyProductTypeDetail;

public interface LxyProductTypeDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int deleteByPrimaryKey(Long typeDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insert(LxyProductTypeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insertSelective(LxyProductTypeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	LxyProductTypeDetail selectByPrimaryKey(Long typeDetailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKeySelective(LxyProductTypeDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type_detail
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKey(LxyProductTypeDetail record);
}