package com.lxy.mapper;

import java.util.List;
import java.util.Map;

import com.lxy.model.LxyProductType;

public interface LxyProductTypeMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int deleteByPrimaryKey(Long typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insert(LxyProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insertSelective(LxyProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	LxyProductType selectByPrimaryKey(Long typeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKeySelective(LxyProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product_type
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKey(LxyProductType record);

	/**
	 * 加载产品类型
	 * @param param
	 * @return
	 */
	public List<Map<String, Object>> loadProductType(Map<String, Object> param);
	
	/**
	 * 获取根类型 parenttypeId 为空的类型
	 * @param param
	 * @return
	 */
	public List<Map<String, Object>> getRootProductType(Map<String, Object> param);
}