package com.lxy.mapper;

import java.util.List;
import java.util.Map;

import com.lxy.model.LxyProduct;

public interface LxyProductMapper {
	
	/**
	 * get product by params
	 * @param param
	 * @return
	 */
	List<Map<String, Object> > getProductByParams(Map<String, Object> param) ;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int deleteByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insert(LxyProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int insertSelective(LxyProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	LxyProduct selectByPrimaryKey(Long productId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKeySelective(LxyProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_product
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	int updateByPrimaryKey(LxyProduct record);
}