package com.lxy.mapper;

import com.lxy.model.LxyProductColor;

public interface LxyProductColorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int deleteByPrimaryKey(Long colorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int insert(LxyProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int insertSelective(LxyProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    LxyProductColor selectByPrimaryKey(Long colorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int updateByPrimaryKeySelective(LxyProductColor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lxy_product_color
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    int updateByPrimaryKey(LxyProductColor record);
}