package com.lxy.mapper;

import com.lxy.model.LxyRolePrivilegeKey;

public interface LxyRolePrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_role_privilege
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int deleteByPrimaryKey(LxyRolePrivilegeKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_role_privilege
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int insert(LxyRolePrivilegeKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_role_privilege
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int insertSelective(LxyRolePrivilegeKey record);
}