package com.lxy.mapper;

import java.util.List;
import java.util.Map;

import com.lxy.model.LxyProductDetail;
import com.lxy.model.LxyUser;

public interface LxyUserMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int deleteByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int insert(LxyUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int insertSelective(LxyUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	LxyUser selectByPrimaryKey(Long userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int updateByPrimaryKeySelective(LxyUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lxy_user
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	int updateByPrimaryKey(LxyUser record);

/*
    * This method was generated by MyBatis Generator.
    * This method corresponds to the database table lxy_user
    *
    * @mbggenerated Mon Dec 01 21:07:48 CST 2014
    */
   List<LxyUser> getUserByParam(Map<String, Object> param);
}