package com.lxy.model;

import java.util.Date;

public class LxyCompanyNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_ID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Long newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.VERSION
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.UUID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_NAME
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_VALUE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_DESC
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_CONTENT
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_TYPE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.NEWS_URL
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String newsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DELETED_FLAG
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.DETAIL_ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String detailAttribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.PROCESS_STATUS
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.MAKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Date makerOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.MAKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String makerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.CHECKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Date checkerOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.CHECKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String checkerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.CREATE_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Date createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.CREATE_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.MODIFY_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Date modifyOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.MODIFY_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.AUTHORIZER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private String authorizerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_company_news.AUTHORIZER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    private Date authorizerOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_ID
     *
     * @return the value of lxy_company_news.NEWS_ID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Long getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_ID
     *
     * @param newsId the value for lxy_company_news.NEWS_ID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsId(Long newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.VERSION
     *
     * @return the value of lxy_company_news.VERSION
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.VERSION
     *
     * @param version the value for lxy_company_news.VERSION
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.UUID
     *
     * @return the value of lxy_company_news.UUID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.UUID
     *
     * @param uuid the value for lxy_company_news.UUID
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_NAME
     *
     * @return the value of lxy_company_news.NEWS_NAME
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsName() {
        return newsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_NAME
     *
     * @param newsName the value for lxy_company_news.NEWS_NAME
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsName(String newsName) {
        this.newsName = newsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_VALUE
     *
     * @return the value of lxy_company_news.NEWS_VALUE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsValue() {
        return newsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_VALUE
     *
     * @param newsValue the value for lxy_company_news.NEWS_VALUE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsValue(String newsValue) {
        this.newsValue = newsValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_DESC
     *
     * @return the value of lxy_company_news.NEWS_DESC
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsDesc() {
        return newsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_DESC
     *
     * @param newsDesc the value for lxy_company_news.NEWS_DESC
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsDesc(String newsDesc) {
        this.newsDesc = newsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_CONTENT
     *
     * @return the value of lxy_company_news.NEWS_CONTENT
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_CONTENT
     *
     * @param newsContent the value for lxy_company_news.NEWS_CONTENT
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_TYPE
     *
     * @return the value of lxy_company_news.NEWS_TYPE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_TYPE
     *
     * @param newsType the value for lxy_company_news.NEWS_TYPE
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.NEWS_URL
     *
     * @return the value of lxy_company_news.NEWS_URL
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getNewsUrl() {
        return newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.NEWS_URL
     *
     * @param newsUrl the value for lxy_company_news.NEWS_URL
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DELETED_FLAG
     *
     * @return the value of lxy_company_news.DELETED_FLAG
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DELETED_FLAG
     *
     * @param deletedFlag the value for lxy_company_news.DELETED_FLAG
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE1
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute1() {
        return detailAttribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE1
     *
     * @param detailAttribute1 the value for lxy_company_news.DETAIL_ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute1(String detailAttribute1) {
        this.detailAttribute1 = detailAttribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE2
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute2() {
        return detailAttribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE2
     *
     * @param detailAttribute2 the value for lxy_company_news.DETAIL_ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute2(String detailAttribute2) {
        this.detailAttribute2 = detailAttribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE3
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute3() {
        return detailAttribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE3
     *
     * @param detailAttribute3 the value for lxy_company_news.DETAIL_ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute3(String detailAttribute3) {
        this.detailAttribute3 = detailAttribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE4
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute4() {
        return detailAttribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE4
     *
     * @param detailAttribute4 the value for lxy_company_news.DETAIL_ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute4(String detailAttribute4) {
        this.detailAttribute4 = detailAttribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE5
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute5() {
        return detailAttribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE5
     *
     * @param detailAttribute5 the value for lxy_company_news.DETAIL_ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute5(String detailAttribute5) {
        this.detailAttribute5 = detailAttribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.DETAIL_ATTRIBUTE6
     *
     * @return the value of lxy_company_news.DETAIL_ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getDetailAttribute6() {
        return detailAttribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.DETAIL_ATTRIBUTE6
     *
     * @param detailAttribute6 the value for lxy_company_news.DETAIL_ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setDetailAttribute6(String detailAttribute6) {
        this.detailAttribute6 = detailAttribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.PROCESS_STATUS
     *
     * @return the value of lxy_company_news.PROCESS_STATUS
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.PROCESS_STATUS
     *
     * @param processStatus the value for lxy_company_news.PROCESS_STATUS
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.MAKER_ON
     *
     * @return the value of lxy_company_news.MAKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Date getMakerOn() {
        return makerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.MAKER_ON
     *
     * @param makerOn the value for lxy_company_news.MAKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setMakerOn(Date makerOn) {
        this.makerOn = makerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.MAKER_BY
     *
     * @return the value of lxy_company_news.MAKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getMakerBy() {
        return makerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.MAKER_BY
     *
     * @param makerBy the value for lxy_company_news.MAKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setMakerBy(String makerBy) {
        this.makerBy = makerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.CHECKER_ON
     *
     * @return the value of lxy_company_news.CHECKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Date getCheckerOn() {
        return checkerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.CHECKER_ON
     *
     * @param checkerOn the value for lxy_company_news.CHECKER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setCheckerOn(Date checkerOn) {
        this.checkerOn = checkerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.CHECKER_BY
     *
     * @return the value of lxy_company_news.CHECKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getCheckerBy() {
        return checkerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.CHECKER_BY
     *
     * @param checkerBy the value for lxy_company_news.CHECKER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setCheckerBy(String checkerBy) {
        this.checkerBy = checkerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.CREATE_ON
     *
     * @return the value of lxy_company_news.CREATE_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.CREATE_ON
     *
     * @param createOn the value for lxy_company_news.CREATE_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.CREATE_BY
     *
     * @return the value of lxy_company_news.CREATE_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.CREATE_BY
     *
     * @param createBy the value for lxy_company_news.CREATE_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.MODIFY_ON
     *
     * @return the value of lxy_company_news.MODIFY_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Date getModifyOn() {
        return modifyOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.MODIFY_ON
     *
     * @param modifyOn the value for lxy_company_news.MODIFY_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setModifyOn(Date modifyOn) {
        this.modifyOn = modifyOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.MODIFY_BY
     *
     * @return the value of lxy_company_news.MODIFY_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.MODIFY_BY
     *
     * @param modifyBy the value for lxy_company_news.MODIFY_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.AUTHORIZER_BY
     *
     * @return the value of lxy_company_news.AUTHORIZER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public String getAuthorizerBy() {
        return authorizerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.AUTHORIZER_BY
     *
     * @param authorizerBy the value for lxy_company_news.AUTHORIZER_BY
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setAuthorizerBy(String authorizerBy) {
        this.authorizerBy = authorizerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_company_news.AUTHORIZER_ON
     *
     * @return the value of lxy_company_news.AUTHORIZER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public Date getAuthorizerOn() {
        return authorizerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_company_news.AUTHORIZER_ON
     *
     * @param authorizerOn the value for lxy_company_news.AUTHORIZER_ON
     *
     * @mbggenerated Thu Dec 11 14:28:00 CST 2014
     */
    public void setAuthorizerOn(Date authorizerOn) {
        this.authorizerOn = authorizerOn;
    }
}