package com.lxy.model;

import java.util.Date;

public class LxyProductDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long detailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PRODUCT_SIZE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String productSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PRODUCT_COLOR_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long productColorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PRODUCT_COLOR_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String productColorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PRODUCT_COLOR_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String productColorValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.AMT
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String amt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String deletedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PRODUCT_IMAGE_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String productImagePath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String detailAttribute6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String processStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date makerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String makerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date checkerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String checkerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date createOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date modifyOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String authorizerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date authorizerOn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ID
	 * @return  the value of lxy_product_detail.DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getDetailId() {
		return detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ID
	 * @param detailId  the value for lxy_product_detail.DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailId(Long detailId) {
		this.detailId = detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.VERSION
	 * @return  the value of lxy_product_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.VERSION
	 * @param version  the value for lxy_product_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.UUID
	 * @return  the value of lxy_product_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.UUID
	 * @param uuid  the value for lxy_product_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_NAME
	 * @return  the value of lxy_product_detail.DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailName() {
		return detailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_NAME
	 * @param detailName  the value for lxy_product_detail.DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailName(String detailName) {
		this.detailName = detailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_VALUE
	 * @return  the value of lxy_product_detail.DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailValue() {
		return detailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_VALUE
	 * @param detailValue  the value for lxy_product_detail.DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailValue(String detailValue) {
		this.detailValue = detailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_DESC
	 * @return  the value of lxy_product_detail.DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailDesc() {
		return detailDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_DESC
	 * @param detailDesc  the value for lxy_product_detail.DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailDesc(String detailDesc) {
		this.detailDesc = detailDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PRODUCT_SIZE
	 * @return  the value of lxy_product_detail.PRODUCT_SIZE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProductSize() {
		return productSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PRODUCT_SIZE
	 * @param productSize  the value for lxy_product_detail.PRODUCT_SIZE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProductSize(String productSize) {
		this.productSize = productSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PRODUCT_COLOR_ID
	 * @return  the value of lxy_product_detail.PRODUCT_COLOR_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getProductColorId() {
		return productColorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PRODUCT_COLOR_ID
	 * @param productColorId  the value for lxy_product_detail.PRODUCT_COLOR_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProductColorId(Long productColorId) {
		this.productColorId = productColorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PRODUCT_COLOR_NAME
	 * @return  the value of lxy_product_detail.PRODUCT_COLOR_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProductColorName() {
		return productColorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PRODUCT_COLOR_NAME
	 * @param productColorName  the value for lxy_product_detail.PRODUCT_COLOR_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProductColorName(String productColorName) {
		this.productColorName = productColorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PRODUCT_COLOR_VALUE
	 * @return  the value of lxy_product_detail.PRODUCT_COLOR_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProductColorValue() {
		return productColorValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PRODUCT_COLOR_VALUE
	 * @param productColorValue  the value for lxy_product_detail.PRODUCT_COLOR_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProductColorValue(String productColorValue) {
		this.productColorValue = productColorValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.AMT
	 * @return  the value of lxy_product_detail.AMT
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getAmt() {
		return amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.AMT
	 * @param amt  the value for lxy_product_detail.AMT
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAmt(String amt) {
		this.amt = amt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DELETED_FLAG
	 * @return  the value of lxy_product_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DELETED_FLAG
	 * @param deletedFlag  the value for lxy_product_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDeletedFlag(String deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PRODUCT_IMAGE_PATH
	 * @return  the value of lxy_product_detail.PRODUCT_IMAGE_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProductImagePath() {
		return productImagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PRODUCT_IMAGE_PATH
	 * @param productImagePath  the value for lxy_product_detail.PRODUCT_IMAGE_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProductImagePath(String productImagePath) {
		this.productImagePath = productImagePath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE1
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute1() {
		return detailAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE1
	 * @param detailAttribute1  the value for lxy_product_detail.DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute1(String detailAttribute1) {
		this.detailAttribute1 = detailAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE2
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute2() {
		return detailAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE2
	 * @param detailAttribute2  the value for lxy_product_detail.DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute2(String detailAttribute2) {
		this.detailAttribute2 = detailAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE3
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute3() {
		return detailAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE3
	 * @param detailAttribute3  the value for lxy_product_detail.DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute3(String detailAttribute3) {
		this.detailAttribute3 = detailAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE4
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute4() {
		return detailAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE4
	 * @param detailAttribute4  the value for lxy_product_detail.DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute4(String detailAttribute4) {
		this.detailAttribute4 = detailAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE5
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute5() {
		return detailAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE5
	 * @param detailAttribute5  the value for lxy_product_detail.DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute5(String detailAttribute5) {
		this.detailAttribute5 = detailAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE6
	 * @return  the value of lxy_product_detail.DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDetailAttribute6() {
		return detailAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.DETAIL_ATTRIBUTE6
	 * @param detailAttribute6  the value for lxy_product_detail.DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDetailAttribute6(String detailAttribute6) {
		this.detailAttribute6 = detailAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.PROCESS_STATUS
	 * @return  the value of lxy_product_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.PROCESS_STATUS
	 * @param processStatus  the value for lxy_product_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.MAKER_ON
	 * @return  the value of lxy_product_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getMakerOn() {
		return makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.MAKER_ON
	 * @param makerOn  the value for lxy_product_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerOn(Date makerOn) {
		this.makerOn = makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.MAKER_BY
	 * @return  the value of lxy_product_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getMakerBy() {
		return makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.MAKER_BY
	 * @param makerBy  the value for lxy_product_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerBy(String makerBy) {
		this.makerBy = makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.CHECKER_ON
	 * @return  the value of lxy_product_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCheckerOn() {
		return checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.CHECKER_ON
	 * @param checkerOn  the value for lxy_product_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerOn(Date checkerOn) {
		this.checkerOn = checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.CHECKER_BY
	 * @return  the value of lxy_product_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCheckerBy() {
		return checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.CHECKER_BY
	 * @param checkerBy  the value for lxy_product_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerBy(String checkerBy) {
		this.checkerBy = checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.CREATE_ON
	 * @return  the value of lxy_product_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCreateOn() {
		return createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.CREATE_ON
	 * @param createOn  the value for lxy_product_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.CREATE_BY
	 * @return  the value of lxy_product_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.CREATE_BY
	 * @param createBy  the value for lxy_product_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.MODIFY_ON
	 * @return  the value of lxy_product_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getModifyOn() {
		return modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.MODIFY_ON
	 * @param modifyOn  the value for lxy_product_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.MODIFY_BY
	 * @return  the value of lxy_product_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.MODIFY_BY
	 * @param modifyBy  the value for lxy_product_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.AUTHORIZER_BY
	 * @return  the value of lxy_product_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getAuthorizerBy() {
		return authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.AUTHORIZER_BY
	 * @param authorizerBy  the value for lxy_product_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerBy(String authorizerBy) {
		this.authorizerBy = authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_detail.AUTHORIZER_ON
	 * @return  the value of lxy_product_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getAuthorizerOn() {
		return authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_detail.AUTHORIZER_ON
	 * @param authorizerOn  the value for lxy_product_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerOn(Date authorizerOn) {
		this.authorizerOn = authorizerOn;
	}
}