package com.lxy.model;

import java.util.Date;

public class LxyProductType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long typeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long typeDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.PARENT_TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long parentTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String deletedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeFolderPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.TYPE_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeAttribute6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String processStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date makerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String makerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date checkerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String checkerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date createOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date modifyOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String authorizerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date authorizerOn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ID
	 * @return  the value of lxy_product_type.TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ID
	 * @param typeId  the value for lxy_product_type.TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.VERSION
	 * @return  the value of lxy_product_type.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.VERSION
	 * @param version  the value for lxy_product_type.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.UUID
	 * @return  the value of lxy_product_type.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.UUID
	 * @param uuid  the value for lxy_product_type.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_DETAIL_ID
	 * @return  the value of lxy_product_type.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getTypeDetailId() {
		return typeDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_DETAIL_ID
	 * @param typeDetailId  the value for lxy_product_type.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailId(Long typeDetailId) {
		this.typeDetailId = typeDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.PARENT_TYPE_ID
	 * @return  the value of lxy_product_type.PARENT_TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getParentTypeId() {
		return parentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.PARENT_TYPE_ID
	 * @param parentTypeId  the value for lxy_product_type.PARENT_TYPE_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setParentTypeId(Long parentTypeId) {
		this.parentTypeId = parentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_NAME
	 * @return  the value of lxy_product_type.TYPE_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_NAME
	 * @param typeName  the value for lxy_product_type.TYPE_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_VALUE
	 * @return  the value of lxy_product_type.TYPE_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeValue() {
		return typeValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_VALUE
	 * @param typeValue  the value for lxy_product_type.TYPE_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeValue(String typeValue) {
		this.typeValue = typeValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_DESC
	 * @return  the value of lxy_product_type.TYPE_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDesc() {
		return typeDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_DESC
	 * @param typeDesc  the value for lxy_product_type.TYPE_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDesc(String typeDesc) {
		this.typeDesc = typeDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.DELETED_FLAG
	 * @return  the value of lxy_product_type.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.DELETED_FLAG
	 * @param deletedFlag  the value for lxy_product_type.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDeletedFlag(String deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_FOLDER_PATH
	 * @return  the value of lxy_product_type.TYPE_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeFolderPath() {
		return typeFolderPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_FOLDER_PATH
	 * @param typeFolderPath  the value for lxy_product_type.TYPE_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeFolderPath(String typeFolderPath) {
		this.typeFolderPath = typeFolderPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE1
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute1() {
		return typeAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE1
	 * @param typeAttribute1  the value for lxy_product_type.TYPE_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute1(String typeAttribute1) {
		this.typeAttribute1 = typeAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE2
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute2() {
		return typeAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE2
	 * @param typeAttribute2  the value for lxy_product_type.TYPE_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute2(String typeAttribute2) {
		this.typeAttribute2 = typeAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE3
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute3() {
		return typeAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE3
	 * @param typeAttribute3  the value for lxy_product_type.TYPE_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute3(String typeAttribute3) {
		this.typeAttribute3 = typeAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE4
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute4() {
		return typeAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE4
	 * @param typeAttribute4  the value for lxy_product_type.TYPE_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute4(String typeAttribute4) {
		this.typeAttribute4 = typeAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE5
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute5() {
		return typeAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE5
	 * @param typeAttribute5  the value for lxy_product_type.TYPE_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute5(String typeAttribute5) {
		this.typeAttribute5 = typeAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.TYPE_ATTRIBUTE6
	 * @return  the value of lxy_product_type.TYPE_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeAttribute6() {
		return typeAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.TYPE_ATTRIBUTE6
	 * @param typeAttribute6  the value for lxy_product_type.TYPE_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeAttribute6(String typeAttribute6) {
		this.typeAttribute6 = typeAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.PROCESS_STATUS
	 * @return  the value of lxy_product_type.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.PROCESS_STATUS
	 * @param processStatus  the value for lxy_product_type.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.MAKER_ON
	 * @return  the value of lxy_product_type.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getMakerOn() {
		return makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.MAKER_ON
	 * @param makerOn  the value for lxy_product_type.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerOn(Date makerOn) {
		this.makerOn = makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.MAKER_BY
	 * @return  the value of lxy_product_type.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getMakerBy() {
		return makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.MAKER_BY
	 * @param makerBy  the value for lxy_product_type.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerBy(String makerBy) {
		this.makerBy = makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.CHECKER_ON
	 * @return  the value of lxy_product_type.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCheckerOn() {
		return checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.CHECKER_ON
	 * @param checkerOn  the value for lxy_product_type.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerOn(Date checkerOn) {
		this.checkerOn = checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.CHECKER_BY
	 * @return  the value of lxy_product_type.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCheckerBy() {
		return checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.CHECKER_BY
	 * @param checkerBy  the value for lxy_product_type.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerBy(String checkerBy) {
		this.checkerBy = checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.CREATE_ON
	 * @return  the value of lxy_product_type.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCreateOn() {
		return createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.CREATE_ON
	 * @param createOn  the value for lxy_product_type.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.CREATE_BY
	 * @return  the value of lxy_product_type.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.CREATE_BY
	 * @param createBy  the value for lxy_product_type.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.MODIFY_ON
	 * @return  the value of lxy_product_type.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getModifyOn() {
		return modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.MODIFY_ON
	 * @param modifyOn  the value for lxy_product_type.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.MODIFY_BY
	 * @return  the value of lxy_product_type.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.MODIFY_BY
	 * @param modifyBy  the value for lxy_product_type.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.AUTHORIZER_BY
	 * @return  the value of lxy_product_type.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getAuthorizerBy() {
		return authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.AUTHORIZER_BY
	 * @param authorizerBy  the value for lxy_product_type.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerBy(String authorizerBy) {
		this.authorizerBy = authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type.AUTHORIZER_ON
	 * @return  the value of lxy_product_type.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getAuthorizerOn() {
		return authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type.AUTHORIZER_ON
	 * @param authorizerOn  the value for lxy_product_type.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerOn(Date authorizerOn) {
		this.authorizerOn = authorizerOn;
	}
}