package com.lxy.model;

import java.util.Date;

public class LxyProductTypeDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Long typeDetailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String deletedFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailFolderPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String typeDetailAttribute6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String processStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date makerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String makerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date checkerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String checkerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date createOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date modifyOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private String authorizerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_product_type_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	private Date authorizerOn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ID
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Long getTypeDetailId() {
		return typeDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ID
	 * @param typeDetailId  the value for lxy_product_type_detail.TYPE_DETAIL_ID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailId(Long typeDetailId) {
		this.typeDetailId = typeDetailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.VERSION
	 * @return  the value of lxy_product_type_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.VERSION
	 * @param version  the value for lxy_product_type_detail.VERSION
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.UUID
	 * @return  the value of lxy_product_type_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.UUID
	 * @param uuid  the value for lxy_product_type_detail.UUID
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_NAME
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailName() {
		return typeDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_NAME
	 * @param typeDetailName  the value for lxy_product_type_detail.TYPE_DETAIL_NAME
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailName(String typeDetailName) {
		this.typeDetailName = typeDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_VALUE
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailValue() {
		return typeDetailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_VALUE
	 * @param typeDetailValue  the value for lxy_product_type_detail.TYPE_DETAIL_VALUE
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailValue(String typeDetailValue) {
		this.typeDetailValue = typeDetailValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_DESC
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailDesc() {
		return typeDetailDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_DESC
	 * @param typeDetailDesc  the value for lxy_product_type_detail.TYPE_DETAIL_DESC
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailDesc(String typeDetailDesc) {
		this.typeDetailDesc = typeDetailDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.DELETED_FLAG
	 * @return  the value of lxy_product_type_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getDeletedFlag() {
		return deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.DELETED_FLAG
	 * @param deletedFlag  the value for lxy_product_type_detail.DELETED_FLAG
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setDeletedFlag(String deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_FOLDER_PATH
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailFolderPath() {
		return typeDetailFolderPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_FOLDER_PATH
	 * @param typeDetailFolderPath  the value for lxy_product_type_detail.TYPE_DETAIL_FOLDER_PATH
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailFolderPath(String typeDetailFolderPath) {
		this.typeDetailFolderPath = typeDetailFolderPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE1
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute1() {
		return typeDetailAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE1
	 * @param typeDetailAttribute1  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE1
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute1(String typeDetailAttribute1) {
		this.typeDetailAttribute1 = typeDetailAttribute1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE2
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute2() {
		return typeDetailAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE2
	 * @param typeDetailAttribute2  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE2
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute2(String typeDetailAttribute2) {
		this.typeDetailAttribute2 = typeDetailAttribute2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE3
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute3() {
		return typeDetailAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE3
	 * @param typeDetailAttribute3  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE3
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute3(String typeDetailAttribute3) {
		this.typeDetailAttribute3 = typeDetailAttribute3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE4
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute4() {
		return typeDetailAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE4
	 * @param typeDetailAttribute4  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE4
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute4(String typeDetailAttribute4) {
		this.typeDetailAttribute4 = typeDetailAttribute4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE5
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute5() {
		return typeDetailAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE5
	 * @param typeDetailAttribute5  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE5
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute5(String typeDetailAttribute5) {
		this.typeDetailAttribute5 = typeDetailAttribute5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE6
	 * @return  the value of lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getTypeDetailAttribute6() {
		return typeDetailAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE6
	 * @param typeDetailAttribute6  the value for lxy_product_type_detail.TYPE_DETAIL_ATTRIBUTE6
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setTypeDetailAttribute6(String typeDetailAttribute6) {
		this.typeDetailAttribute6 = typeDetailAttribute6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.PROCESS_STATUS
	 * @return  the value of lxy_product_type_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.PROCESS_STATUS
	 * @param processStatus  the value for lxy_product_type_detail.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.MAKER_ON
	 * @return  the value of lxy_product_type_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getMakerOn() {
		return makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.MAKER_ON
	 * @param makerOn  the value for lxy_product_type_detail.MAKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerOn(Date makerOn) {
		this.makerOn = makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.MAKER_BY
	 * @return  the value of lxy_product_type_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getMakerBy() {
		return makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.MAKER_BY
	 * @param makerBy  the value for lxy_product_type_detail.MAKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setMakerBy(String makerBy) {
		this.makerBy = makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.CHECKER_ON
	 * @return  the value of lxy_product_type_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCheckerOn() {
		return checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.CHECKER_ON
	 * @param checkerOn  the value for lxy_product_type_detail.CHECKER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerOn(Date checkerOn) {
		this.checkerOn = checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.CHECKER_BY
	 * @return  the value of lxy_product_type_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCheckerBy() {
		return checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.CHECKER_BY
	 * @param checkerBy  the value for lxy_product_type_detail.CHECKER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCheckerBy(String checkerBy) {
		this.checkerBy = checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.CREATE_ON
	 * @return  the value of lxy_product_type_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getCreateOn() {
		return createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.CREATE_ON
	 * @param createOn  the value for lxy_product_type_detail.CREATE_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.CREATE_BY
	 * @return  the value of lxy_product_type_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.CREATE_BY
	 * @param createBy  the value for lxy_product_type_detail.CREATE_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.MODIFY_ON
	 * @return  the value of lxy_product_type_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getModifyOn() {
		return modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.MODIFY_ON
	 * @param modifyOn  the value for lxy_product_type_detail.MODIFY_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.MODIFY_BY
	 * @return  the value of lxy_product_type_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.MODIFY_BY
	 * @param modifyBy  the value for lxy_product_type_detail.MODIFY_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.AUTHORIZER_BY
	 * @return  the value of lxy_product_type_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public String getAuthorizerBy() {
		return authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.AUTHORIZER_BY
	 * @param authorizerBy  the value for lxy_product_type_detail.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerBy(String authorizerBy) {
		this.authorizerBy = authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_product_type_detail.AUTHORIZER_ON
	 * @return  the value of lxy_product_type_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public Date getAuthorizerOn() {
		return authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_product_type_detail.AUTHORIZER_ON
	 * @param authorizerOn  the value for lxy_product_type_detail.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 11 14:28:00 CST 2014
	 */
	public void setAuthorizerOn(Date authorizerOn) {
		this.authorizerOn = authorizerOn;
	}
}