package com.lxy.model;

public class LxyRolePrivilegeKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_role_privilege.PRIVILEGE_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String privilegeValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_role_privilege.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Long roleId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_role_privilege.PRIVILEGE_VALUE
	 * @return  the value of lxy_role_privilege.PRIVILEGE_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getPrivilegeValue() {
		return privilegeValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_role_privilege.PRIVILEGE_VALUE
	 * @param privilegeValue  the value for lxy_role_privilege.PRIVILEGE_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setPrivilegeValue(String privilegeValue) {
		this.privilegeValue = privilegeValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_role_privilege.ROLE_ID
	 * @return  the value of lxy_role_privilege.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_role_privilege.ROLE_ID
	 * @param roleId  the value for lxy_role_privilege.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
}