package com.lxy.model;

import java.util.Date;

public class LxyRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.ROLE_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.VERSION
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.ROLE_NAME
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.LONG_DESC
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String longDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.PROCESS_STATUS
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.OLD_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Long oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.CREATE_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Date createOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.CREATE_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.MODIFY_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Date modifyOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.MODIFY_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String modifyBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.MAKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Date makerOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.MAKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String makerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.CHECKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Date checkerOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.CHECKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String checkerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.AUTHORIZER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private String authorizerBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lxy_role.AUTHORIZER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    private Date authorizerOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.ROLE_ID
     *
     * @return the value of lxy_role.ROLE_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.ROLE_ID
     *
     * @param roleId the value for lxy_role.ROLE_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.VERSION
     *
     * @return the value of lxy_role.VERSION
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.VERSION
     *
     * @param version the value for lxy_role.VERSION
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.ROLE_NAME
     *
     * @return the value of lxy_role.ROLE_NAME
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.ROLE_NAME
     *
     * @param roleName the value for lxy_role.ROLE_NAME
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.LONG_DESC
     *
     * @return the value of lxy_role.LONG_DESC
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getLongDesc() {
        return longDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.LONG_DESC
     *
     * @param longDesc the value for lxy_role.LONG_DESC
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.PROCESS_STATUS
     *
     * @return the value of lxy_role.PROCESS_STATUS
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.PROCESS_STATUS
     *
     * @param processStatus the value for lxy_role.PROCESS_STATUS
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.OLD_ID
     *
     * @return the value of lxy_role.OLD_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Long getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.OLD_ID
     *
     * @param oldId the value for lxy_role.OLD_ID
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setOldId(Long oldId) {
        this.oldId = oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.CREATE_ON
     *
     * @return the value of lxy_role.CREATE_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.CREATE_ON
     *
     * @param createOn the value for lxy_role.CREATE_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.CREATE_BY
     *
     * @return the value of lxy_role.CREATE_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.CREATE_BY
     *
     * @param createBy the value for lxy_role.CREATE_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.MODIFY_ON
     *
     * @return the value of lxy_role.MODIFY_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Date getModifyOn() {
        return modifyOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.MODIFY_ON
     *
     * @param modifyOn the value for lxy_role.MODIFY_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setModifyOn(Date modifyOn) {
        this.modifyOn = modifyOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.MODIFY_BY
     *
     * @return the value of lxy_role.MODIFY_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.MODIFY_BY
     *
     * @param modifyBy the value for lxy_role.MODIFY_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.MAKER_ON
     *
     * @return the value of lxy_role.MAKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Date getMakerOn() {
        return makerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.MAKER_ON
     *
     * @param makerOn the value for lxy_role.MAKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setMakerOn(Date makerOn) {
        this.makerOn = makerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.MAKER_BY
     *
     * @return the value of lxy_role.MAKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getMakerBy() {
        return makerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.MAKER_BY
     *
     * @param makerBy the value for lxy_role.MAKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setMakerBy(String makerBy) {
        this.makerBy = makerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.CHECKER_ON
     *
     * @return the value of lxy_role.CHECKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Date getCheckerOn() {
        return checkerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.CHECKER_ON
     *
     * @param checkerOn the value for lxy_role.CHECKER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setCheckerOn(Date checkerOn) {
        this.checkerOn = checkerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.CHECKER_BY
     *
     * @return the value of lxy_role.CHECKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getCheckerBy() {
        return checkerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.CHECKER_BY
     *
     * @param checkerBy the value for lxy_role.CHECKER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setCheckerBy(String checkerBy) {
        this.checkerBy = checkerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.AUTHORIZER_BY
     *
     * @return the value of lxy_role.AUTHORIZER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public String getAuthorizerBy() {
        return authorizerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.AUTHORIZER_BY
     *
     * @param authorizerBy the value for lxy_role.AUTHORIZER_BY
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setAuthorizerBy(String authorizerBy) {
        this.authorizerBy = authorizerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lxy_role.AUTHORIZER_ON
     *
     * @return the value of lxy_role.AUTHORIZER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public Date getAuthorizerOn() {
        return authorizerOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lxy_role.AUTHORIZER_ON
     *
     * @param authorizerOn the value for lxy_role.AUTHORIZER_ON
     *
     * @mbggenerated Sat Nov 29 12:08:38 CST 2014
     */
    public void setAuthorizerOn(Date authorizerOn) {
        this.authorizerOn = authorizerOn;
    }
}