package com.lxy.model;

import java.util.Date;

public class LxySystemParameter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.PARA_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Long paraId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.PARA_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String paraName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.PARA_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String paraValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.PARA_DESC
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String paraDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String processStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date makerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String makerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date checkerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String checkerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date createOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date modifyOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String authorizerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date authorizerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_system_parameter.SYSTEM_PARA
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Short systemPara;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.PARA_ID
	 * @return  the value of lxy_system_parameter.PARA_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Long getParaId() {
		return paraId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.PARA_ID
	 * @param paraId  the value for lxy_system_parameter.PARA_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setParaId(Long paraId) {
		this.paraId = paraId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.VERSION
	 * @return  the value of lxy_system_parameter.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.VERSION
	 * @param version  the value for lxy_system_parameter.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.PARA_NAME
	 * @return  the value of lxy_system_parameter.PARA_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getParaName() {
		return paraName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.PARA_NAME
	 * @param paraName  the value for lxy_system_parameter.PARA_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setParaName(String paraName) {
		this.paraName = paraName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.PARA_VALUE
	 * @return  the value of lxy_system_parameter.PARA_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getParaValue() {
		return paraValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.PARA_VALUE
	 * @param paraValue  the value for lxy_system_parameter.PARA_VALUE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setParaValue(String paraValue) {
		this.paraValue = paraValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.PARA_DESC
	 * @return  the value of lxy_system_parameter.PARA_DESC
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getParaDesc() {
		return paraDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.PARA_DESC
	 * @param paraDesc  the value for lxy_system_parameter.PARA_DESC
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setParaDesc(String paraDesc) {
		this.paraDesc = paraDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.PROCESS_STATUS
	 * @return  the value of lxy_system_parameter.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.PROCESS_STATUS
	 * @param processStatus  the value for lxy_system_parameter.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.MAKER_ON
	 * @return  the value of lxy_system_parameter.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getMakerOn() {
		return makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.MAKER_ON
	 * @param makerOn  the value for lxy_system_parameter.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setMakerOn(Date makerOn) {
		this.makerOn = makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.MAKER_BY
	 * @return  the value of lxy_system_parameter.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getMakerBy() {
		return makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.MAKER_BY
	 * @param makerBy  the value for lxy_system_parameter.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setMakerBy(String makerBy) {
		this.makerBy = makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.CHECKER_ON
	 * @return  the value of lxy_system_parameter.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getCheckerOn() {
		return checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.CHECKER_ON
	 * @param checkerOn  the value for lxy_system_parameter.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCheckerOn(Date checkerOn) {
		this.checkerOn = checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.CHECKER_BY
	 * @return  the value of lxy_system_parameter.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getCheckerBy() {
		return checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.CHECKER_BY
	 * @param checkerBy  the value for lxy_system_parameter.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCheckerBy(String checkerBy) {
		this.checkerBy = checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.CREATE_ON
	 * @return  the value of lxy_system_parameter.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getCreateOn() {
		return createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.CREATE_ON
	 * @param createOn  the value for lxy_system_parameter.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.CREATE_BY
	 * @return  the value of lxy_system_parameter.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.CREATE_BY
	 * @param createBy  the value for lxy_system_parameter.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.MODIFY_ON
	 * @return  the value of lxy_system_parameter.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getModifyOn() {
		return modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.MODIFY_ON
	 * @param modifyOn  the value for lxy_system_parameter.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.MODIFY_BY
	 * @return  the value of lxy_system_parameter.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.MODIFY_BY
	 * @param modifyBy  the value for lxy_system_parameter.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.AUTHORIZER_BY
	 * @return  the value of lxy_system_parameter.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getAuthorizerBy() {
		return authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.AUTHORIZER_BY
	 * @param authorizerBy  the value for lxy_system_parameter.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAuthorizerBy(String authorizerBy) {
		this.authorizerBy = authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.AUTHORIZER_ON
	 * @return  the value of lxy_system_parameter.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getAuthorizerOn() {
		return authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.AUTHORIZER_ON
	 * @param authorizerOn  the value for lxy_system_parameter.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAuthorizerOn(Date authorizerOn) {
		this.authorizerOn = authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_system_parameter.SYSTEM_PARA
	 * @return  the value of lxy_system_parameter.SYSTEM_PARA
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Short getSystemPara() {
		return systemPara;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_system_parameter.SYSTEM_PARA
	 * @param systemPara  the value for lxy_system_parameter.SYSTEM_PARA
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setSystemPara(Short systemPara) {
		this.systemPara = systemPara;
	}
}