package com.lxy.model;

import java.util.Date;

public class LxyUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.USER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.OLD_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Long oldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.OPER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String operId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.USER_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.REAL_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String realName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.GENDER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LOGIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String loginFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LOGIN_IP_ADDRESS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String loginIpAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String processStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LAST_LOGIN_TIME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LAN_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String lanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.ENGLISH_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String englishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.EXPIRE_DATE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date expireDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.QUESTION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String question;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.ANSWER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String answer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.EMAIL
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.CHECK_TYPES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String checkTypes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date makerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String makerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date checkerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String checkerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date createOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String authorizerBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date authorizerOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Date modifyOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String modifyBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.USER_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LOGIN_FAILURE_TIMES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer loginFailureTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.BACK_UP_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String backUpPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.DEPT_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer deptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.BRANCH_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer branchId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LEFT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String leftPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.RIGHT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String rightPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.ADMIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String adminFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.LOCALE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String locale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lxy_user.USER_IP
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	private String userIp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.USER_ID
	 * @return  the value of lxy_user.USER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.USER_ID
	 * @param userId  the value for lxy_user.USER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.OLD_ID
	 * @return  the value of lxy_user.OLD_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Long getOldId() {
		return oldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.OLD_ID
	 * @param oldId  the value for lxy_user.OLD_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setOldId(Long oldId) {
		this.oldId = oldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.VERSION
	 * @return  the value of lxy_user.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.VERSION
	 * @param version  the value for lxy_user.VERSION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.OPER_ID
	 * @return  the value of lxy_user.OPER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getOperId() {
		return operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.OPER_ID
	 * @param operId  the value for lxy_user.OPER_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setOperId(String operId) {
		this.operId = operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.USER_NAME
	 * @return  the value of lxy_user.USER_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.USER_NAME
	 * @param userName  the value for lxy_user.USER_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.REAL_NAME
	 * @return  the value of lxy_user.REAL_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getRealName() {
		return realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.REAL_NAME
	 * @param realName  the value for lxy_user.REAL_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setRealName(String realName) {
		this.realName = realName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.GENDER
	 * @return  the value of lxy_user.GENDER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.GENDER
	 * @param gender  the value for lxy_user.GENDER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.PASSWORD
	 * @return  the value of lxy_user.PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.PASSWORD
	 * @param password  the value for lxy_user.PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LOGIN_FLAG
	 * @return  the value of lxy_user.LOGIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getLoginFlag() {
		return loginFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LOGIN_FLAG
	 * @param loginFlag  the value for lxy_user.LOGIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLoginFlag(String loginFlag) {
		this.loginFlag = loginFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LOGIN_IP_ADDRESS
	 * @return  the value of lxy_user.LOGIN_IP_ADDRESS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getLoginIpAddress() {
		return loginIpAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LOGIN_IP_ADDRESS
	 * @param loginIpAddress  the value for lxy_user.LOGIN_IP_ADDRESS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLoginIpAddress(String loginIpAddress) {
		this.loginIpAddress = loginIpAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.PROCESS_STATUS
	 * @return  the value of lxy_user.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getProcessStatus() {
		return processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.PROCESS_STATUS
	 * @param processStatus  the value for lxy_user.PROCESS_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setProcessStatus(String processStatus) {
		this.processStatus = processStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LAST_LOGIN_TIME
	 * @return  the value of lxy_user.LAST_LOGIN_TIME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LAST_LOGIN_TIME
	 * @param lastLoginTime  the value for lxy_user.LAST_LOGIN_TIME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LAN_ID
	 * @return  the value of lxy_user.LAN_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getLanId() {
		return lanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LAN_ID
	 * @param lanId  the value for lxy_user.LAN_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLanId(String lanId) {
		this.lanId = lanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.ENGLISH_NAME
	 * @return  the value of lxy_user.ENGLISH_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getEnglishName() {
		return englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.ENGLISH_NAME
	 * @param englishName  the value for lxy_user.ENGLISH_NAME
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setEnglishName(String englishName) {
		this.englishName = englishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.EXPIRE_DATE
	 * @return  the value of lxy_user.EXPIRE_DATE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getExpireDate() {
		return expireDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.EXPIRE_DATE
	 * @param expireDate  the value for lxy_user.EXPIRE_DATE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.QUESTION
	 * @return  the value of lxy_user.QUESTION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getQuestion() {
		return question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.QUESTION
	 * @param question  the value for lxy_user.QUESTION
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.ANSWER
	 * @return  the value of lxy_user.ANSWER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getAnswer() {
		return answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.ANSWER
	 * @param answer  the value for lxy_user.ANSWER
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.EMAIL
	 * @return  the value of lxy_user.EMAIL
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.EMAIL
	 * @param email  the value for lxy_user.EMAIL
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.CHECK_TYPES
	 * @return  the value of lxy_user.CHECK_TYPES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getCheckTypes() {
		return checkTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.CHECK_TYPES
	 * @param checkTypes  the value for lxy_user.CHECK_TYPES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCheckTypes(String checkTypes) {
		this.checkTypes = checkTypes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.MAKER_ON
	 * @return  the value of lxy_user.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getMakerOn() {
		return makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.MAKER_ON
	 * @param makerOn  the value for lxy_user.MAKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setMakerOn(Date makerOn) {
		this.makerOn = makerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.MAKER_BY
	 * @return  the value of lxy_user.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getMakerBy() {
		return makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.MAKER_BY
	 * @param makerBy  the value for lxy_user.MAKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setMakerBy(String makerBy) {
		this.makerBy = makerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.CHECKER_ON
	 * @return  the value of lxy_user.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getCheckerOn() {
		return checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.CHECKER_ON
	 * @param checkerOn  the value for lxy_user.CHECKER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCheckerOn(Date checkerOn) {
		this.checkerOn = checkerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.CHECKER_BY
	 * @return  the value of lxy_user.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getCheckerBy() {
		return checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.CHECKER_BY
	 * @param checkerBy  the value for lxy_user.CHECKER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCheckerBy(String checkerBy) {
		this.checkerBy = checkerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.CREATE_ON
	 * @return  the value of lxy_user.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getCreateOn() {
		return createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.CREATE_ON
	 * @param createOn  the value for lxy_user.CREATE_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCreateOn(Date createOn) {
		this.createOn = createOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.CREATE_BY
	 * @return  the value of lxy_user.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.CREATE_BY
	 * @param createBy  the value for lxy_user.CREATE_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.AUTHORIZER_BY
	 * @return  the value of lxy_user.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getAuthorizerBy() {
		return authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.AUTHORIZER_BY
	 * @param authorizerBy  the value for lxy_user.AUTHORIZER_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAuthorizerBy(String authorizerBy) {
		this.authorizerBy = authorizerBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.AUTHORIZER_ON
	 * @return  the value of lxy_user.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getAuthorizerOn() {
		return authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.AUTHORIZER_ON
	 * @param authorizerOn  the value for lxy_user.AUTHORIZER_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAuthorizerOn(Date authorizerOn) {
		this.authorizerOn = authorizerOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.MODIFY_ON
	 * @return  the value of lxy_user.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Date getModifyOn() {
		return modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.MODIFY_ON
	 * @param modifyOn  the value for lxy_user.MODIFY_ON
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setModifyOn(Date modifyOn) {
		this.modifyOn = modifyOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.MODIFY_BY
	 * @return  the value of lxy_user.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getModifyBy() {
		return modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.MODIFY_BY
	 * @param modifyBy  the value for lxy_user.MODIFY_BY
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setModifyBy(String modifyBy) {
		this.modifyBy = modifyBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.USER_STATUS
	 * @return  the value of lxy_user.USER_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.USER_STATUS
	 * @param userStatus  the value for lxy_user.USER_STATUS
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LOGIN_FAILURE_TIMES
	 * @return  the value of lxy_user.LOGIN_FAILURE_TIMES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getLoginFailureTimes() {
		return loginFailureTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LOGIN_FAILURE_TIMES
	 * @param loginFailureTimes  the value for lxy_user.LOGIN_FAILURE_TIMES
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLoginFailureTimes(Integer loginFailureTimes) {
		this.loginFailureTimes = loginFailureTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.BACK_UP_PASSWORD
	 * @return  the value of lxy_user.BACK_UP_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getBackUpPassword() {
		return backUpPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.BACK_UP_PASSWORD
	 * @param backUpPassword  the value for lxy_user.BACK_UP_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setBackUpPassword(String backUpPassword) {
		this.backUpPassword = backUpPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.DEPT_ID
	 * @return  the value of lxy_user.DEPT_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.DEPT_ID
	 * @param deptId  the value for lxy_user.DEPT_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.BRANCH_ID
	 * @return  the value of lxy_user.BRANCH_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getBranchId() {
		return branchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.BRANCH_ID
	 * @param branchId  the value for lxy_user.BRANCH_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setBranchId(Integer branchId) {
		this.branchId = branchId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.ROLE_ID
	 * @return  the value of lxy_user.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.ROLE_ID
	 * @param roleId  the value for lxy_user.ROLE_ID
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LEFT_PASSWORD
	 * @return  the value of lxy_user.LEFT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getLeftPassword() {
		return leftPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LEFT_PASSWORD
	 * @param leftPassword  the value for lxy_user.LEFT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLeftPassword(String leftPassword) {
		this.leftPassword = leftPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.RIGHT_PASSWORD
	 * @return  the value of lxy_user.RIGHT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getRightPassword() {
		return rightPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.RIGHT_PASSWORD
	 * @param rightPassword  the value for lxy_user.RIGHT_PASSWORD
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setRightPassword(String rightPassword) {
		this.rightPassword = rightPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.ADMIN_FLAG
	 * @return  the value of lxy_user.ADMIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getAdminFlag() {
		return adminFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.ADMIN_FLAG
	 * @param adminFlag  the value for lxy_user.ADMIN_FLAG
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setAdminFlag(String adminFlag) {
		this.adminFlag = adminFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.LOCALE
	 * @return  the value of lxy_user.LOCALE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getLocale() {
		return locale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.LOCALE
	 * @param locale  the value for lxy_user.LOCALE
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setLocale(String locale) {
		this.locale = locale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lxy_user.USER_IP
	 * @return  the value of lxy_user.USER_IP
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public String getUserIp() {
		return userIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lxy_user.USER_IP
	 * @param userIp  the value for lxy_user.USER_IP
	 * @mbggenerated  Thu Dec 04 16:19:17 CST 2014
	 */
	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}
}